databases:
  - name: notes
    databaseName: notes_db
    user: notes
    plan: free

services:
  - type: web
    name: notes
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        value: "sqlite3://storage/production.sqlite3"
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
