default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  adapter: postgresql
  database: chgk_buff
  username: <%= ENV['PG_USER']%>
  password: <%= ENV['PG_PASS']%>
  host: localhost
  port: 5432
  pool: 5

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  url: <%= ENV['DATABASE_URL']%>
